# Generated by Django 4.2.25 on 2025-12-01 10:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_alter_participant_email_alter_participant_phone'),
    ]

    operations = [
        migrations.AddField(
            model_name='participant',
            name='has_won',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='participant',
            name='reward',
            field=models.PositiveBigIntegerField(blank=True, null=True),
        ),
    ]
