# Generated by Django 4.2.25 on 2025-12-04 06:38

from django.db import migrations, models
import match_title_win.storages_backends


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_participant_played_at_participant_time_taken_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='participant',
            name='invoice',
            field=models.FileField(blank=True, null=True, storage=match_title_win.storages_backends.R2PublicStorage(), upload_to='assets/invoices/'),
        ),
        migrations.AddField(
            model_name='participant',
            name='invoice_public_url',
            field=models.URLField(blank=True, max_length=500, null=True),
        ),
    ]
