# Generated by Django 4.2.25 on 2025-12-04 07:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_participant_invoice_participant_invoice_public_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='participant',
            name='amount_spent',
            field=models.PositiveBigIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='participant',
            name='retailer',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
