# Generated by Django 4.2.25 on 2025-12-04 11:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_participant_amount_spent_participant_retailer'),
    ]

    operations = [
        migrations.AddField(
            model_name='participant',
            name='has_played',
            field=models.BooleanField(default=False),
        ),
    ]
