# Generated by Django 4.2.25 on 2025-12-04 12:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_participant_has_played'),
    ]

    operations = [
        migrations.AlterField(
            model_name='participant',
            name='has_played',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
    ]
