# Generated by Django 4.2.25 on 2025-12-04 12:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_alter_participant_has_played'),
    ]

    operations = [
        migrations.CreateModel(
            name='PrizeConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reset_date', models.DateTimeField(blank=True, null=True)),
            ],
        ),
    ]
