# Generated by Django 4.2.25 on 2025-12-05 06:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0010_prizeconfig'),
    ]

    operations = [
        migrations.AlterField(
            model_name='prize',
            name='amount',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
