# Generated by Django 4.2.25 on 2025-12-05 07:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0011_alter_prize_amount'),
    ]

    operations = [
        migrations.CreateModel(
            name='ConsolationPrize',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('quantity', models.PositiveIntegerField(default=0)),
            ],
        ),
    ]
