# Generated by Django 4.2.25 on 2025-12-05 09:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0012_consolationprize'),
    ]

    operations = [
        migrations.AddField(
            model_name='participant',
            name='is_prize_claimed',
            field=models.BooleanField(default=False),
        ),
    ]
