# Generated by Django 4.2.25 on 2025-12-05 10:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0013_participant_is_prize_claimed'),
    ]

    operations = [
        migrations.AddField(
            model_name='prize',
            name='quantity_limit',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
