# Generated by Django 4.2.25 on 2025-12-06 16:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0014_prize_quantity_limit'),
    ]

    operations = [
        migrations.CreateModel(
            name='PrizeResetLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('recorded_at', models.DateTimeField(auto_now_add=True)),
                ('snapshot', models.JSONField()),
            ],
        ),
    ]
